apiVersion: v1
kind: Pod
metadata:
  name: init-con
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sh","-c", "echo 'Initalization started ...'; sleep 10; echo 'Initization completed.'"] 
  containers:
  - name:  main-container
    image:  busybox:latest
    command: ["sh","-c", "echo 'Main container started'"]