apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  namespace: demo 
  lables: 
    app: local 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath: /mnt/data
  
