apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: demo 
spec:
  resources:
    requests:
      storage: 1 Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
