apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-f
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-container
          image: gowdavaishu34/my-python-app:latest
          ports:
            - containerPort: 5000
