kind: Service
apiVersion: v1
metadata:
  name: service-demo
  namespace: demo 
spec:
  selector: 
      app: demo
  ports:
    - protocol: TCP 
      port: 5000
      targetPort: 5000
  type: ClusterIP 