kind: Service
apiVersion: v1
metadata:
  name:  mysql-serivce
  namespace: demo
spec:
  selector:
    app:  myapp
  type: ClusterIP 
  ports:
  - name:  mysql
    protocol: TCP
    port: 3306
    targetPort:  3306
