apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
  namespace: demo 
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: mysql-serivce
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 3306
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: musql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
